import pytest

from src import day_7

input_1_day_7 = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

input_2_day_7 = """.......S.......
...............
.......^.......
...............
......^.^......
...............
.....^.^.^.....
...............
....^.^...^....
...............
...^.^...^.^...
...............
..^...^.....^..
...............
.^.^.^.^.^...^.
..............."""

output_day_7_star_1 = 21
output_day_7_star_2 = 40

day_7_star_1_test_input = [(input_1_day_7, output_day_7_star_1)]
day_7_star_2_test_input = [(input_2_day_7, output_day_7_star_2)]


@pytest.mark.parametrize("puzzle_input, output", day_7_star_1_test_input)
def test_day_7_star_1(puzzle_input: str, output: int):
    assert day_7.compute_star_1(puzzle_input) == output


@pytest.mark.parametrize("puzzle_input, output", day_7_star_2_test_input)
def test_day_7_star_2(puzzle_input: str, output: int):
    assert day_7.compute_star_2(puzzle_input) == output
